### ISSUE TITLE
Installation failed with official ubuntu sd card, looks like at some point numpy 2.0.0 installed from some dependency and this breaks overlay loading. and installation

### ISSUE THREAD

**Issue by alexian79** [Xilinx/Kria-PYNQ#44]
I am new to Pynq, just tried to install it on KV260 and it fails. tried it 2 times in a row with fresh install and did followed extra steps from booting your starter kit.

- pynq-helloworld (source: pynq_helloworld)
- kv260 (source: kv260)
- pynq-dpu (source: pynq_dpu)
- pynq_composable (source: pynq_composable)
- pynq_peripherals (source: pynq_peripherals)
Do you want to proceed? [Y/n] Delivering notebooks '/root/jupyter_notebooks/pynq-helloworld'...
Delivering notebooks '/root/jupyter_notebooks/kv260'...
Delivering notebooks '/root/jupyter_notebooks/pynq-dpu'...
Delivering notebooks '/root/jupyter_notebooks/pynq_composable'...

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/usr/local/share/pynq-venv/bin/pynq-get-notebooks", line 8, in <module>
    sys.exit(main())
  File "/usr/local/share/pynq-venv/lib/python3.10/site-packages/pynq/_cli/get_notebooks.py", line 262, in main
    ext_mod = ext.load()
  File "/usr/local/share/pynq-venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2465, in load
    return self.resolve()
  File "/usr/local/share/pynq-venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2471, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/share/pynq-venv/lib/python3.10/site-packages/pynq_composable/__init__.py", line 8, in <module>
    from .apps import PipelineApp
  File "/usr/local/share/pynq-venv/lib/python3.10/site-packages/pynq_composable/apps.py", line 7, in <module>
    from .video import VideoStream, VSource, VSink
  File "/usr/local/share/pynq-venv/lib/python3.10/site-packages/pynq_composable/video.py", line 6, in <module>
    import cv2
AttributeError: _ARRAY_API not found
Traceback (most recent call last):
  File "/usr/local/share/pynq-venv/bin/pynq-get-notebooks", line 8, in <module>
    sys.exit(main())
  File "/usr/local/share/pynq-venv/lib/python3.10/site-packages/pynq/_cli/get_notebooks.py", line 308, in main
    raise e
  File "/usr/local/share/pynq-venv/lib/python3.10/site-packages/pynq/_cli/get_notebooks.py", line 262, in main
    ext_mod = ext.load()
  File "/usr/local/share/pynq-venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2465, in load
    return self.resolve()
  File "/usr/local/share/pynq-venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2471, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/share/pynq-venv/lib/python3.10/site-packages/pynq_composable/__init__.py", line 8, in <module>
    from .apps import PipelineApp
  File "/usr/local/share/pynq-venv/lib/python3.10/site-packages/pynq_composable/apps.py", line 7, in <module>
    from .video import VideoStream, VSource, VSink
  File "/usr/local/share/pynq-venv/lib/python3.10/site-packages/pynq_composable/video.py", line 6, in <module>
    import cv2
ImportError: numpy.core.multiarray failed to import

**Comment by skalade** [comment]
Hi @alexian79, yeah the Numpy 2.0 upgrade has been causing havoc across a few repos unfortunately! I just merged a PR that should fix it for the Kria-PYNQ install https://github.com/Xilinx/Kria-PYNQ/commit/21bf5e18a6dba20babe99108ac697d2cdc49645f

Please pull the change and try installing again, it works for me on a fresh Kria image.

Thanks
Shawn

**Comment by alexian79** [comment]
Great, I was able just pull and rerun install.sh script and it fixed the issue. Thank you.

**Comment by skalade** [comment]
Great to hear! Thanks for reporting.

Closing since issue is resolved.
